source /mnt/si0021787ci2/default/lzq/deepresearch/deltatrace_rl_20260922/receipts/environment-only-20260930/entry/metax-entry.env.sh
/opt/conda/bin/python - <<'PY'

from pathlib import Path
import hashlib,json,os,resource,time
root=Path('/mnt/si0021787ci2/default/lzq/deepresearch/deltatrace_rl_20260922');receipt=root/'receipts/appworld-official-whitening-20261006-v2';prepared=json.loads((receipt/'prepared.json').read_bytes());plan=json.loads((receipt/'launch-plan.json').read_bytes());task='AppWorld';devices=[2,3];entry=Path(prepared['entry']);verl=Path(prepared['verl_root']);output=Path(plan['working_directory']);checkpoint=Path(plan['checkpoint_root']);source={};prior_source=json.loads(Path(prepared['prior_source_receipt']).read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
exec(compile("env = os.environ.copy()\nenv.update(prepared.get('resource_environment', {}))\nenv.update(VERL_ROOT=str(verl), DT_ROOT=prepared['dt_root'], DT_ENTRY_ROOT=str(entry), CUDA_VISIBLE_DEVICES=','.join(map(str, devices)))\nenv.pop('MACA_VISIBLE_DEVICES', None)\nextra_path = []\nif task == 'AppWorld':\n    source.update(loop_root=prepared['loop_root'], author_sha256=prepared.get('author_sha256', prior_source['author_sha256']))\n    if 'author_readiness_binding' in prepared:\n        source['author_readiness_binding'] = prepared['author_readiness_binding']\n    for name, expected in source['author_sha256'].items():\n        assert sha(Path(prepared['loop_root']) / name) == expected, name\n    env.update(LOOP_ROOT=prepared['loop_root'], APPWORLD_ROOT=str(root / 'receipts/environment-only-20260930/loop-entry/appworld-root'))\n    extra_path.append(prepared['loop_root'])\n    launcher = entry / 'launch_appworld_native.py'\n    argv = [env['VENV_PYTHON'], str(launcher), '--output', str(output), '--resume-from', str(checkpoint)]\nelse:\n    prior_launch = read(Path(old['output']) / 'launch.json')\n    data = old['argv'][old['argv'].index('--data') + 1]\n    agentgym = prior_launch['options']['+env.textcraft']['owner_root']\n    env['AGENTGYM_RL_ROOT'] = agentgym\n    source.update(agentgym_root=agentgym, prior_source_receipt=str(Path(old['output']) / 'source.json'), prior_source_sha256=sha(Path(old['output']) / 'source.json'))\n    launcher = entry / 'launch_textcraft_native.py'\n    argv = [env['VENV_PYTHON'], str(launcher), '--data', data, '--output', str(output), '--resume-from', str(checkpoint)]\nprovisioned_dt_root = Path(os.environ['DT_ROOT'])\ndt_paths = {str(provisioned_dt_root): prepared['dt_root'], str(provisioned_dt_root / 'experiments/rl'): str(Path(prepared['dt_root']) / 'experiments/rl')}\ninherited_paths = [dt_paths.get(path, path) for path in env['PYTHONPATH'].split(':')]\nenv['PYTHONPATH'] = ':'.join([str(entry), str(verl), *extra_path, *inherited_paths])\nsource['pythonpath'] = env['PYTHONPATH']\nsource['resource_environment'] = prepared.get('resource_environment', {})\nsource['resume_launcher'] = dict(path=str(launcher), sha256=sha(launcher))",'actual_submitter_environment_AST','exec'))
diff={k:dict(actual=env.get(k),prepared=v) for k,v in plan['environment'].items() if env.get(k)!=v}
record=dict(observed_unix=time.time(),submission_boundary_source_sha256='64c10036389de83e33c345251f25fbaa0afbef613d6c42659d7f1215abee769f',environment_AST_sha256=hashlib.sha256("env = os.environ.copy()\nenv.update(prepared.get('resource_environment', {}))\nenv.update(VERL_ROOT=str(verl), DT_ROOT=prepared['dt_root'], DT_ENTRY_ROOT=str(entry), CUDA_VISIBLE_DEVICES=','.join(map(str, devices)))\nenv.pop('MACA_VISIBLE_DEVICES', None)\nextra_path = []\nif task == 'AppWorld':\n    source.update(loop_root=prepared['loop_root'], author_sha256=prepared.get('author_sha256', prior_source['author_sha256']))\n    if 'author_readiness_binding' in prepared:\n        source['author_readiness_binding'] = prepared['author_readiness_binding']\n    for name, expected in source['author_sha256'].items():\n        assert sha(Path(prepared['loop_root']) / name) == expected, name\n    env.update(LOOP_ROOT=prepared['loop_root'], APPWORLD_ROOT=str(root / 'receipts/environment-only-20260930/loop-entry/appworld-root'))\n    extra_path.append(prepared['loop_root'])\n    launcher = entry / 'launch_appworld_native.py'\n    argv = [env['VENV_PYTHON'], str(launcher), '--output', str(output), '--resume-from', str(checkpoint)]\nelse:\n    prior_launch = read(Path(old['output']) / 'launch.json')\n    data = old['argv'][old['argv'].index('--data') + 1]\n    agentgym = prior_launch['options']['+env.textcraft']['owner_root']\n    env['AGENTGYM_RL_ROOT'] = agentgym\n    source.update(agentgym_root=agentgym, prior_source_receipt=str(Path(old['output']) / 'source.json'), prior_source_sha256=sha(Path(old['output']) / 'source.json'))\n    launcher = entry / 'launch_textcraft_native.py'\n    argv = [env['VENV_PYTHON'], str(launcher), '--data', data, '--output', str(output), '--resume-from', str(checkpoint)]\nprovisioned_dt_root = Path(os.environ['DT_ROOT'])\ndt_paths = {str(provisioned_dt_root): prepared['dt_root'], str(provisioned_dt_root / 'experiments/rl'): str(Path(prepared['dt_root']) / 'experiments/rl')}\ninherited_paths = [dt_paths.get(path, path) for path in env['PYTHONPATH'].split(':')]\nenv['PYTHONPATH'] = ':'.join([str(entry), str(verl), *extra_path, *inherited_paths])\nsource['pythonpath'] = env['PYTHONPATH']\nsource['resource_environment'] = prepared.get('resource_environment', {})\nsource['resume_launcher'] = dict(path=str(launcher), sha256=sha(launcher))".encode()).hexdigest(),environment_differences=diff,argv_equal=(argv==plan['argv']),source_author_interface=source['author_sha256']['phi_agents/appworld/interface.py'],host_cache_release=env.get('VERL_RELEASE_UNUSED_HOST_CACHE'),max_rss_bytes=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024,model_calls=0,GPU_calls=0,process_submissions=0,source_or_manifest_writes=0,scope='Execute the actual submitter environment/argv AST only; compare against actual CPU-verified plan. Does not launch.')
print(json.dumps(record));assert not diff;assert record['argv_equal'];assert record['source_author_interface']=='17adc301aae395b789b5528abc167fd025b6cbb22379e954c600ed586987610e';assert record['host_cache_release']=='1';assert 'MACA_VISIBLE_DEVICES' not in env

PY
